/**
 * Other Flows — shared lucide icon resolver.
 *
 * `FlowModule.icon` / `FlowAction.icon` are plain strings written by the FLOW
 * DATA agent (a parallel session) into a file this session does not own. We
 * cannot guarantee at compile time which exact PascalCase name they picked,
 * so this map casts a wide net over every icon name a module/action in this
 * spec could plausibly use, and `resolveIcon()` falls back to `Sparkles`
 * (logged once, not thrown) for anything unmapped — a typo in someone else's
 * data file must never blank the screen.
 *
 * Every key below was verified against the installed lucide-react package
 * (`node_modules/lucide-react/dist/esm/icons/*.js`) before use.
 */
import {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  Ban,
  BarChart3,
  Bot,
  BookmarkPlus,
  Boxes,
  Calendar,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronRight,
  Clapperboard,
  Clock,
  Coins,
  ExternalLink,
  Eye,
  Film,
  Flag,
  Flame,
  Folder,
  FolderClosed,
  FolderOpen,
  Gauge,
  Globe,
  HelpCircle,
  History,
  Image as ImageIcon,
  Info,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Library,
  Lightbulb,
  Link,
  Link2,
  Lock,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  MoreHorizontal,
  MoreVertical,
  Newspaper,
  Package,
  PackageSearch,
  Play,
  PlayCircle,
  Presentation,
  Radar,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Repeat2,
  Rocket,
  RotateCcw,
  RotateCw,
  Rss,
  Scissors,
  Search,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  Sparkle,
  Sparkles,
  Star,
  Table2,
  Tag,
  Tags,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  Users,
  Video,
  Wand2,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * String key → component. Keys are the exact PascalCase lucide export name.
 * Add to this list rather than inventing a parallel naming scheme — it keeps
 * the data file free to just write real lucide names.
 */
export const ICONS: Record<string, LucideIcon> = {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  Ban,
  BarChart3,
  Bot,
  BookmarkPlus,
  Boxes,
  Calendar,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronRight,
  Clapperboard,
  Clock,
  Coins,
  ExternalLink,
  Eye,
  Film,
  Flag,
  Flame,
  Folder,
  FolderClosed,
  FolderOpen,
  Gauge,
  Globe,
  HelpCircle,
  History,
  Image: ImageIcon,
  ImageIcon,
  Info,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Library,
  Lightbulb,
  Link,
  Link2,
  Lock,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  MoreHorizontal,
  MoreVertical,
  Newspaper,
  Package,
  PackageSearch,
  Play,
  PlayCircle,
  Presentation,
  Radar,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Repeat2,
  Rocket,
  RotateCcw,
  RotateCw,
  Rss,
  Scissors,
  Search,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  Sparkle,
  Sparkles,
  Star,
  Table2,
  Tag,
  Tags,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  Users,
  Video,
  Wand2,
  Workflow,
  Zap,
};

const warned = new Set<string>();

/** Resolves a data-file icon string to a component. Never throws. */
export function resolveIcon(name: string | undefined): LucideIcon {
  if (name && ICONS[name]) return ICONS[name];
  if (name && !warned.has(name) && import.meta.env.DEV) {
    // eslint-disable-next-line no-console
    console.warn(`[flows/icons] Unmapped icon "${name}" — add it to src/genie6/flows/icons.tsx. Falling back to Sparkles.`);
    warned.add(name);
  }
  return Sparkles;
}
