import { useState } from "react";

import { AuthNav } from "@/pages/Auth";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";
import qrCode from "@/assets/auth/2fa-qr.svg";

/**
 * TwoFactorModal — Figma "Two factor authentication" modal (node
 * 9431:56264, 472x606). Pure UI: Cancel and Verify both just close the
 * modal — there's no backend to verify a code against yet.
 */
export function TwoFactorModal({ nav }: { nav: AuthNav }) {
  const [code, setCode] = useState("");

  return (
    <Dialog
      open
      onOpenChange={(open) => {
        if (!open) nav.closeModal();
      }}
    >
      <DialogContent className="max-w-[472px] gap-0 rounded-2xl p-0">
        <div className="flex flex-col items-center gap-0 pb-4 pt-6">
          <DialogTitle className="text-2xl font-bold text-foreground">
            Two factor authentication
          </DialogTitle>
        </div>

        <div className="flex flex-col items-center gap-4 px-6 pb-6">
          {/* Step 1 — QR code */}
          <div className="flex w-full flex-col items-center gap-4">
            <div className="flex w-full flex-col items-center gap-1 text-center">
              <h3 className="w-full text-base font-semibold tracking-tight text-foreground">
                Step 1: Scan this QR code
              </h3>
              <p className="w-full text-sm text-muted-foreground">
                Scan the following QR code with your authenticator app, such as Google
                Authenticator, Microsoft authenticator, Gauth, etc.
              </p>
            </div>
            <img src={qrCode} alt="Two-factor authentication QR code" className="h-40 w-40" />
          </div>

          <div className="h-px w-full bg-border" />

          {/* Step 2 — verification code */}
          <div className="flex w-full flex-col items-center gap-4 pb-4">
            <div className="flex w-full flex-col items-center gap-1 text-center">
              <h3 className="w-full text-base font-semibold tracking-tight text-foreground">
                Step 2: Enter the one-time code
              </h3>
              <p className="w-full text-sm text-muted-foreground">
                Enter the 6-digit verification code generated by the authenticator app.
              </p>
            </div>
            <InputOTP maxLength={6} value={code} onChange={setCode}>
              <InputOTPGroup className="w-full justify-between gap-2">
                {Array.from({ length: 6 }).map((_, index) => (
                  <InputOTPSlot
                    key={index}
                    index={index}
                    className="h-11 w-11 rounded-lg border first:rounded-lg last:rounded-lg"
                  />
                ))}
              </InputOTPGroup>
            </InputOTP>
          </div>

          <div className="h-px w-full bg-border" />

          {/* Actions */}
          <div className="flex w-full items-center justify-end gap-4 pt-2">
            <Button type="button" variant="outline" onClick={() => nav.closeModal()} className="rounded-lg">
              Cancel
            </Button>
            <Button type="button" onClick={() => nav.closeModal()} className="rounded-lg">
              Verify
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
